#!/bin/sh
#
# @name Twin Tractor
#
# @type Standard Plane
# @class Plane
#
# @output MAIN1 aileron left
# @output MAIN2 aileron right
# @output MAIN3 elevator left
# @output MAIN4 elevator right
# @output MAIN5 throttle left
# @output MAIN6 throttle right
# @output MAIN7 rudder
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Andrew Alarcon <aalarcon3@gatech.edu>
#

sh /etc/init.d/rc.fw_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_AUX_RATE 50
	param set PWM_RATE 50
fi

set MIXER AAEETTR

# Rate must be set by group (see pwm info).
# Throttle is in the same group as servos.
